-- Migration 022: Seed PMMSY subsidy rules, NABARD policy highlights, and Bihar cost benchmarks
-- Sources:
--   PMMSY Operational Guidelines 2020, Dept. of Fisheries, MoFAHD, GoI
--   NABARD Master Circular – Fisheries and Aquaculture Lending
--   NFDB Unit Cost Norms (revised FY2022-23)

INSERT INTO knowledge_rules (
  id_slug, record_type, document_title, source_type, institution,
  scope_type, region_group, state_code, project_types, species,
  metric_name, numeric_value, unit, bucket,
  confidence, freshness, applicability_condition,
  active_for_calculator, active_for_knowledgebase,
  citation_text, citation_section, notes
) VALUES

-- ─── BENEFICIARY SUBSIDY % ────────────────────────────────────────────────────

('rncnaa-beneficiary-subsidy-general',
 'subsidy_rule',
 'PMMSY Operational Guidelines 2020 – Beneficiary Component',
 'GOVERNMENT_NOTIFICATION',
 'Ministry of Fisheries, Animal Husbandry & Dairying, GoI',
 'NATIONAL', NULL, NULL, '["ALL"]', '[]',
 'Beneficiary Subsidy – General Category',
 40, 'PERCENT', 'SUBSIDY',
 'HIGH', 'FY2023-24',
 'General category farmers for freshwater/brackishwater pond culture, RAS, biofloc, cage culture',
 TRUE, TRUE,
 'PMMSY Operational Guidelines Chapter 4, Annexure-I Component C1 & C2',
 'Chapter 4',
 '40% of unit project cost. Beneficiary funds remaining 60% via own contribution + bank loan. Unit cost ceiling varies by activity (₹7L/ha pond culture).'),

('rncnaa-beneficiary-subsidy-priority',
 'subsidy_rule',
 'PMMSY Operational Guidelines 2020 – Beneficiary Component',
 'GOVERNMENT_NOTIFICATION',
 'Ministry of Fisheries, Animal Husbandry & Dairying, GoI',
 'NATIONAL', NULL, NULL, '["ALL"]', '[]',
 'Beneficiary Subsidy – SC/ST/Women Category',
 60, 'PERCENT', 'SUBSIDY',
 'HIGH', 'FY2023-24',
 'SC, ST category farmers and women beneficiaries/SHGs for any PMMSY eligible activity',
 TRUE, TRUE,
 'PMMSY Operational Guidelines Chapter 4, Annexure-I Component C1 & C2',
 'Chapter 4',
 '60% of unit project cost. Higher subsidy to promote inclusive fisheries development. Remaining 40% by beneficiary.'),

-- ─── CENTRAL / STATE FUNDING SHARE ───────────────────────────────────────────

('pmmsy-central-share-standard',
 'subsidy_rule',
 'PMMSY Operational Guidelines 2020 – Funding Pattern',
 'GOVERNMENT_NOTIFICATION',
 'Ministry of Fisheries, Animal Husbandry & Dairying, GoI',
 'REGION_GROUP', 'STANDARD_STATES', NULL, '["ALL"]', '[]',
 'Central Funding Share (Standard)',
 60, 'PERCENT', 'FUNDING_SHARE',
 'HIGH', 'FY2023-24',
 'All states except NE/Hilly states and Union Territories',
 TRUE, TRUE,
 'PMMSY Operational Guidelines 2020 – Funding Pattern Table',
 'Chapter 3',
 'Central Govt provides 60% of the subsidy amount. State Govt provides 40%. Bihar, UP, WB, AP etc. fall under this pattern.'),

('pmmsy-state-share-standard',
 'subsidy_rule',
 'PMMSY Operational Guidelines 2020 – Funding Pattern',
 'GOVERNMENT_NOTIFICATION',
 'Ministry of Fisheries, Animal Husbandry & Dairying, GoI',
 'REGION_GROUP', 'STANDARD_STATES', NULL, '["ALL"]', '[]',
 'State Funding Share (Standard)',
 40, 'PERCENT', 'FUNDING_SHARE',
 'HIGH', 'FY2023-24',
 'All states except NE/Hilly states and Union Territories',
 TRUE, TRUE,
 'PMMSY Operational Guidelines 2020 – Funding Pattern Table',
 'Chapter 3',
 'State Govt provides 40% of the subsidy amount. Paid via State Fisheries Department to beneficiary.'),

('pmmsy-central-share-ne-hilly',
 'subsidy_rule',
 'PMMSY Operational Guidelines 2020 – Funding Pattern NE/Hilly',
 'GOVERNMENT_NOTIFICATION',
 'Ministry of Fisheries, Animal Husbandry & Dairying, GoI',
 'REGION_GROUP', 'NE_HILLY', NULL, '["ALL"]', '[]',
 'Central Funding Share (NE/Hilly)',
 90, 'PERCENT', 'FUNDING_SHARE',
 'HIGH', 'FY2023-24',
 'NE states: AR, AS, MN, ML, MZ, NL, TR, SK; Hilly states: HP, JK, LA, UT',
 TRUE, TRUE,
 'PMMSY Operational Guidelines 2020 – Funding Pattern Table (NE/Hilly provision)',
 'Chapter 3',
 'Special 90:10 ratio to encourage aquaculture development in remote NE and Hilly regions.'),

('pmmsy-state-share-ne-hilly',
 'subsidy_rule',
 'PMMSY Operational Guidelines 2020 – Funding Pattern NE/Hilly',
 'GOVERNMENT_NOTIFICATION',
 'Ministry of Fisheries, Animal Husbandry & Dairying, GoI',
 'REGION_GROUP', 'NE_HILLY', NULL, '["ALL"]', '[]',
 'State Funding Share (NE/Hilly)',
 10, 'PERCENT', 'FUNDING_SHARE',
 'HIGH', 'FY2023-24',
 'NE states and Hilly states only',
 TRUE, TRUE,
 'PMMSY Operational Guidelines 2020 – Funding Pattern Table (NE/Hilly provision)',
 'Chapter 3',
 'State contributes only 10% recognising limited state fiscal capacity in these regions.'),

-- ─── PROJECT-SPECIFIC SUBSIDY RULES ──────────────────────────────────────────

('pmmsy-pond-culture-standard-general',
 'subsidy_rule',
 'PMMSY Component C1 – Freshwater Pond Culture',
 'GOVERNMENT_NOTIFICATION',
 'Ministry of Fisheries, Animal Husbandry & Dairying, GoI',
 'REGION_GROUP', 'STANDARD_STATES', NULL, '["POND_CULTURE"]', '[]',
 'Pond Culture Subsidy – General (Standard States)',
 40, 'PERCENT', 'SUBSIDY',
 'HIGH', 'FY2023-24',
 'New construction or renovation of freshwater fish ponds, hatcheries, nurseries',
 TRUE, TRUE,
 'PMMSY Annexure-I Component C1 – Unit Cost ₹7,00,000/ha',
 'Annexure-I C1',
 '40% subsidy = ₹2.8 lakh/ha. Covers earthwork, inlet/outlet, lime treatment, first stocking.'),

('pmmsy-brackish-standard-general',
 'subsidy_rule',
 'PMMSY Component C2 – Brackishwater Shrimp Culture',
 'GOVERNMENT_NOTIFICATION',
 'Ministry of Fisheries, Animal Husbandry & Dairying, GoI',
 'REGION_GROUP', 'STANDARD_STATES', NULL, '["BRACKISHWATER"]', '[]',
 'Brackishwater Shrimp Culture Subsidy – General (Standard States)',
 40, 'PERCENT', 'SUBSIDY',
 'HIGH', 'FY2023-24',
 'Shrimp/prawn pond construction, aerators, water quality equipment, coastal aquaculture',
 TRUE, TRUE,
 'PMMSY Annexure-I Component C2 – Unit Cost ₹10,00,000/ha',
 'Annexure-I C2',
 '40% subsidy = ₹4 lakh/ha. Higher unit cost due to saline water infrastructure and aerator requirements.'),

-- ─── NABARD POLICY HIGHLIGHTS ────────────────────────────────────────────────

('nabard-margin-money-small-farmer',
 'policy_rule',
 'NABARD Fisheries Scheme – Margin Money Subsidy',
 'INSTITUTIONAL_REPORT',
 'NABARD',
 'NATIONAL', NULL, NULL, '["POND_CULTURE","BRACKISHWATER","ALL"]', '[]',
 'NABARD Margin Money Subsidy – Small & Marginal Farmers',
 25, 'PERCENT', 'NABARD_SUBSIDY',
 'HIGH', 'FY2023-24',
 'Farmers with landholding up to 2 ha; annual family income below ₹1.5 lakh',
 FALSE, TRUE,
 'NABARD Fisheries Circular – Back-ended Capital Subsidy Scheme',
 NULL,
 'Back-ended subsidy released after 3 years of verified operation. Bank provides loan; NABARD refinances. Effective interest rate ~7% p.a. after subvention.'),

('nabard-loan-moratorium',
 'policy_rule',
 'NABARD Fisheries Lending – Moratorium and Repayment Terms',
 'INSTITUTIONAL_REPORT',
 'NABARD',
 'NATIONAL', NULL, NULL, '["ALL"]', '[]',
 'NABARD Loan Moratorium Period',
 2, 'YEARS', 'LOAN_TERMS',
 'HIGH', 'FY2023-24',
 'First-time aquaculture borrowers; farmers establishing new ponds or hatcheries',
 FALSE, TRUE,
 'NABARD Master Circular – Fisheries and Aquaculture Lending',
 NULL,
 'Up to 2-year moratorium (no principal repayment during pond setup/grow-out). Total tenure 7-10 years. Collateral: hypothecation of fish stock + land mortgage.'),

-- ─── BIHAR COST BENCHMARKS ────────────────────────────────────────────────────

('bihar-pond-construction-cost-benchmark',
 'cost_benchmark',
 'NFDB Unit Cost Norms – Freshwater Aquaculture, Bihar',
 'GOVERNMENT_NOTIFICATION',
 'National Fisheries Development Board (NFDB)',
 'STATE', NULL, 'BR', '["POND_CULTURE"]', '[]',
 'Pond Construction & Renovation Cost',
 350000, 'INR_PER_HECTARE', 'CAPEX',
 'MEDIUM', 'FY2022-23',
 'Bihar Gangetic plain; clay-loam soil; ponds 0.2–2 ha size',
 TRUE, TRUE, NULL, NULL,
 'Includes earthwork, dyke compaction, sluice gate, inlet/outlet channels. Excludes aerator and pump.'),

('bihar-fingerling-cost-benchmark',
 'cost_benchmark',
 'NFDB Unit Cost Norms – Bihar Stocking',
 'GOVERNMENT_NOTIFICATION',
 'National Fisheries Development Board (NFDB)',
 'STATE', NULL, 'BR', '["POND_CULTURE"]', '[]',
 'IMC Fingerling Stocking Cost',
 800, 'INR_PER_1000', 'OPEX',
 'MEDIUM', 'FY2022-23',
 'Indian Major Carp (Rohu, Catla, Mrigal) fingerlings 4-6 cm size',
 TRUE, TRUE, NULL, NULL,
 'Bihar hatchery market price. Recommended stocking density 4000-5000/ha polyculture. Source: Bihar Fisheries Dept. hatchery price list.'),

('bihar-fish-feed-cost-benchmark',
 'cost_benchmark',
 'NFDB Unit Cost Norms – Bihar Feed Cost',
 'GOVERNMENT_NOTIFICATION',
 'National Fisheries Development Board (NFDB)',
 'STATE', NULL, 'BR', '["POND_CULTURE"]', '[]',
 'Supplementary Feed Cost (per kg)',
 22, 'INR_PER_KG', 'OPEX',
 'MEDIUM', 'FY2023-24',
 'Mustard oil cake + rice bran mix used as supplementary feed for IMC polyculture',
 TRUE, TRUE, NULL, NULL,
 'Local market average for mustard cake + rice bran blend (1:1 ratio). Pellet feed ₹35-45/kg for intensive systems.'),

-- ─── RISK FLAGS / DISCLAIMERS ─────────────────────────────────────────────────

('pmmsy-state-dbt-delay-risk',
 'risk_flag',
 'PMMSY Implementation Review – DBT Delay Risk',
 'INSTITUTIONAL_REPORT',
 'NITI Aayog / State Fisheries Depts.',
 'NATIONAL', NULL, NULL, '["ALL"]', '[]',
 'Subsidy Disbursement Delay Risk',
 NULL, NULL, NULL, 'DELAY_RISK',
 'MEDIUM', 'FY2023-24',
 'State DBT pipeline backlogs reported in Bihar, UP, WB, Odisha',
 FALSE, TRUE,
 'NITI Aayog PMMSY Review Report 2022',
 NULL,
 'Subsidy may take 6-18 months after project completion verification. Plan working capital accordingly. Always apply through official State Fisheries Department portal.')

ON CONFLICT (id_slug) DO UPDATE SET
  numeric_value    = EXCLUDED.numeric_value,
  notes            = EXCLUDED.notes,
  freshness        = EXCLUDED.freshness,
  updated_at       = NOW();
